# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'

variables:
  subcondir: "$(Build.SourcesDirectory)\\cmd\\subcon"
  subconcpp: "$(subcondir)\\*.cpp"
  subconexe: "$(Build.BinariesDirectory)\\subcon.exe"

steps:
- script: |
    dir "c:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary"
    call "c:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
    echo cl.exe /nologo /O1 /EHsc /MD /permissive- /W4 /DUNICODE /D_UNICODE /std:c++17 $(subconcpp) /link /out:$(subconexe) /subsystem:console
    cl.exe /nologo /O1 /EHsc /MD /permissive- /W4 /DUNICODE /D_UNICODE /std:c++17 $(subconcpp) /link /out:$(subconexe) /subsystem:console

- task: GitHubRelease@0
  #condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/release-v')
  inputs:
    gitHubConnection: 'MichaelUrman'
    repositoryName: $(Build.Repository.Name)
    action: create
    tagSource: manual
    tag: $(Build.BuildNumber)
    assets: $(Build.BinariesDirectory)/*.exe
    isDraft: true
    isPreRelease: true
